---
- name: GIT Installation
  hosts: all
  become: yes
  become_user: root
  tasks:
    - name: "Check for GIT"
      ansible.builtin.shell: "git --version"
      ignore_errors: yes
      register: is_git_installed

    - name: "Update apt repo"
      ansible.builtin.shell: "apt-get update"
      when: is_git_installed.rc != 0

    - name: "Install GIT"
      ansible.builtin.shell: "apt-get install git -y"
      when: is_git_installed.rc != 0
